<?php

$title = 'My Users';
$this->headTitle($title);
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div>
<h1>"Hello, Laminas!"</h1>
</div>



<h1><?= $this->escapeHtml($title) ?></h1>


<table class="table">
<tr>
    <th>User</th>
    <th>Email</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($this->users as $user) : ?>
    <tr>
    <td><?= $user['id']; ?></td>
        <td><?= $user['name']; ?></td>
        <td><?= $user['email']; ?></td>
        
    </tr>
<?php endforeach; ?>

</table>